export default {
  title: 'Referral',
  income: 'Total Revenue',
  settlementIn45Days: 'Settled after 30 days',
  settlementDescription: 'Referral ad revenue settlement',
  noSettlementHistory: 'No settlement history.',
  group: 'My Group',
  settlement: 'Settlement List',
  rank: 'Rank',
  referralLabel: 'Referral',
  pending: 'Pending',
  paid: 'Paid',
  fromUserRevenue: 'Revenue generated by {{name}}',
  source_nas: 'AR Ad (Nasmedia)',
  source_pocr: 'AR Ad (PointClick)',
  source_xplay_zone1: 'Xplay Zone 1',
  source_xplay_zone2: 'Xplay Zone 2',
  source_recommend: 'Referral signup',
  source_attendance: 'Attendance',
  source_referral_share: 'Referral share',
  rewardAmount: 'Reward amount',
};



