import { CountryDialCode } from '../types';

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { iso2: 'us', name: 'United States', dialCode: '+1', flagEmoji: '🇺🇸' },
  { iso2: 'ru', name: 'Russia', dialCode: '+7', flagEmoji: '🇷🇺' },
  { iso2: 'eg', name: 'Egypt', dialCode: '+20', flagEmoji: '🇪🇬' },
  { iso2: 'za', name: 'South Africa', dialCode: '+27', flagEmoji: '🇿🇦' },
  { iso2: 'gr', name: 'Greece', dialCode: '+30', flagEmoji: '🇬🇷' },
  { iso2: 'nl', name: 'Netherlands', dialCode: '+31', flagEmoji: '🇳🇱' },
  { iso2: 'be', name: 'Belgium', dialCode: '+32', flagEmoji: '🇧🇪' },
  { iso2: 'fr', name: 'France', dialCode: '+33', flagEmoji: '🇫🇷' },
  { iso2: 'es', name: 'Spain', dialCode: '+34', flagEmoji: '🇪🇸' },
  { iso2: 'hu', name: 'Hungary', dialCode: '+36', flagEmoji: '🇭🇺' },
  { iso2: 'it', name: 'Italy', dialCode: '+39', flagEmoji: '🇮🇹' },
  { iso2: 'ro', name: 'Romania', dialCode: '+40', flagEmoji: '🇷🇴' },
  { iso2: 'ch', name: 'Switzerland', dialCode: '+41', flagEmoji: '🇨🇭' },
  { iso2: 'at', name: 'Austria', dialCode: '+43', flagEmoji: '🇦🇹' },
  { iso2: 'gb', name: 'United Kingdom', dialCode: '+44', flagEmoji: '🇬🇧' },
  { iso2: 'dk', name: 'Denmark', dialCode: '+45', flagEmoji: '🇩🇰' },
  { iso2: 'se', name: 'Sweden', dialCode: '+46', flagEmoji: '🇸🇪' },
  { iso2: 'no', name: 'Norway', dialCode: '+47', flagEmoji: '🇳🇴' },
  { iso2: 'pl', name: 'Poland', dialCode: '+48', flagEmoji: '🇵🇱' },
  { iso2: 'de', name: 'Germany', dialCode: '+49', flagCode: '🇩🇪' },
  { iso2: 'pe', name: 'Peru', dialCode: '+51', flagEmoji: '🇵🇪' },
  { iso2: 'mx', name: 'Mexico', dialCode: '+52', flagEmoji: '🇲🇽' },
  { iso2: 'cu', name: 'Cuba', dialCode: '+53', flagEmoji: '🇨🇺' },
  { iso2: 'ar', name: 'Argentina', dialCode: '+54', flagEmoji: '🇦🇷' },
  { iso2: 'br', name: 'Brazil', dialCode: '+55', flagEmoji: '🇧🇷' },
  { iso2: 'cl', name: 'Chile', dialCode: '+56', flagEmoji: '🇨🇱' },
  { iso2: 'co', name: 'Colombia', dialCode: '+57', flagEmoji: '🇨🇴' },
  { iso2: 've', name: 'Venezuela', dialCode: '+58', flagEmoji: '🇻🇪' },
  { iso2: 'my', name: 'Malaysia', dialCode: '+60', flagEmoji: '🇲🇾' },
  { iso2: 'au', name: 'Australia', dialCode: '+61', flagEmoji: '🇦🇺' },
  { iso2: 'ph', name: 'Philippines', dialCode: '+63', flagEmoji: '🇵🇭' },
  { iso2: 'nz', name: 'New Zealand', dialCode: '+64', flagEmoji: '🇳🇿' },
  { iso2: 'sg', name: 'Singapore', dialCode: '+65', flagEmoji: '🇸🇬' },
  { iso2: 'th', name: 'Thailand', dialCode: '+66', flagEmoji: '🇹🇭' },
  { iso2: 'cy', name: 'Cyprus', dialCode: '+357', flagEmoji: '🇨🇾' },
  { iso2: 'fi', name: 'Finland', dialCode: '+358', flagEmoji: '🇫🇮' },
  { iso2: 'in', name: 'India', dialCode: '+91', flagEmoji: '🇮🇳' },
  { iso2: 'pk', name: 'Pakistan', dialCode: '+92', flagEmoji: '🇵🇰' },
  { iso2: 'af', name: 'Afghanistan', dialCode: '+93', flagEmoji: '🇦🇫' },
  { iso2: 'lk', name: 'Sri Lanka', dialCode: '+94', flagEmoji: '🇱🇰' },
  { iso2: 'mm', name: 'Myanmar', dialCode: '+95', flagEmoji: '🇲🇲' },
  { iso2: 'lb', name: 'Lebanon', dialCode: '+961', flagEmoji: '🇱🇧' },
  { iso2: 'jo', name: 'Jordan', dialCode: '+962', flagEmoji: '🇯🇴' },
  { iso2: 'sy', name: 'Syria', dialCode: '+963', flagEmoji: '🇸🇾' },
  { iso2: 'iq', name: 'Iraq', dialCode: '+964', flagEmoji: '🇮🇶' },
  { iso2: 'kw', name: 'Kuwait', dialCode: '+965', flagEmoji: '🇰🇼' },
  { iso2: 'sa', name: 'Saudi Arabia', dialCode: '+966', flagEmoji: '🇸🇦' },
  { iso2: 'ye', name: 'Yemen', dialCode: '+967', flagEmoji: '🇾🇪' },
  { iso2: 'om', name: 'Oman', dialCode: '+968', flagEmoji: '🇴🇲' },
  { iso2: 'ae', name: 'United Arab Emirates', dialCode: '+971', flagEmoji: '🇦🇪' },
  { iso2: 'il', name: 'Israel', dialCode: '+972', flagEmoji: '🇮🇱' },
  { iso2: 'bh', name: 'Bahrain', dialCode: '+973', flagEmoji: '🇧🇭' },
  { iso2: 'qa', name: 'Qatar', dialCode: '+974', flagEmoji: '🇶🇦' },
  { iso2: 'mn', name: 'Mongolia', dialCode: '+976', flagEmoji: '🇲🇳' },
  { iso2: 'np', name: 'Nepal', dialCode: '+977', flagEmoji: '🇳🇵' },
  { iso2: 'ir', name: 'Iran', dialCode: '+98', flagEmoji: '🇮🇷' },
  { iso2: 'tr', name: 'Turkey', dialCode: '+90', flagEmoji: '🇹🇷' },
  { iso2: 'cn', name: 'China', dialCode: '+86', flagEmoji: '🇨🇳' },
  { iso2: 'jp', name: 'Japan', dialCode: '+81', flagEmoji: '🇯🇵' },
  { iso2: 'kr', name: 'Korea', dialCode: '+82', flagEmoji: '🇰🇷' },
  { iso2: 'vn', name: 'Vietnam', dialCode: '+84', flagEmoji: '🇻🇳' },
  { iso2: 'hk', name: 'Hong Kong', dialCode: '+852', flagEmoji: '🇭🇰' },
  { iso2: 'mo', name: 'Macao', dialCode: '+853', flagEmoji: '🇲🇴' },
  { iso2: 'kh', name: 'Cambodia', dialCode: '+855', flagEmoji: '🇰🇭' },
  { iso2: 'la', name: 'Lao', dialCode: '+856', flagEmoji: '🇱🇦' },
  { iso2: 'bd', name: 'Bangladesh', dialCode: '+880', flagEmoji: '🇧🇩' },
  { iso2: 'tw', name: 'Taiwan', dialCode: '+886', flagEmoji: '🇹🇼' },
  { iso2: 'pt', name: 'Portugal', dialCode: '+351', flagEmoji: '🇵🇹' },
  { iso2: 'is', name: 'Iceland', dialCode: '+354', flagEmoji: '🇮🇸' },
  { iso2: 'al', name: 'Albania', dialCode: '+355', flagEmoji: '🇦🇱' },
  { iso2: 'mt', name: 'Malta', dialCode: '+356', flagEmoji: '🇲🇹' },
  { iso2: 'ie', name: 'Ireland', dialCode: '+353', flagEmoji: '🇮🇪' },
  { iso2: 'ua', name: 'Ukraine', dialCode: '+380', flagEmoji: '🇺🇦' },
  { iso2: 'rs', name: 'Serbia', dialCode: '+381', flagEmoji: '🇷🇸' },
  { iso2: 'me', name: 'Montenegro', dialCode: '+382', flagEmoji: '🇲🇪' },
  { iso2: 'hr', name: 'Croatia', dialCode: '+385', flagEmoji: '🇭🇷' },
  { iso2: 'si', name: 'Slovenia', dialCode: '+386', flagEmoji: '🇸🇮' },
  { iso2: 'ba', name: 'Bosnia-Herzegovina', dialCode: '+387', flagEmoji: '🇧🇦' },
  { iso2: 'mk', name: 'Macedonia', dialCode: '+389', flagEmoji: '🇲🇰' },
  { iso2: 'lt', name: 'Lithuania', dialCode: '+370', flagEmoji: '🇱🇹' },
  { iso2: 'lv', name: 'Latvia', dialCode: '+371', flagEmoji: '🇱🇻' },
  { iso2: 'ee', name: 'Estonia', dialCode: '+372', flagEmoji: '🇪🇪' },
  { iso2: 'md', name: 'Moldova', dialCode: '+373', flagEmoji: '🇲🇩' },
  { iso2: 'am', name: 'Armenia', dialCode: '+374', flagEmoji: '🇦🇲' },
  { iso2: 'by', name: 'Belarus', dialCode: '+375', flagEmoji: '🇧🇾' },
  { iso2: 'ad', name: 'Andorra', dialCode: '+376', flagEmoji: '🇦🇩' },
  { iso2: 'mc', name: 'Monaco', dialCode: '+377', flagEmoji: '🇲🇨' },
  { iso2: 'sm', name: 'San Marino', dialCode: '+378', flagEmoji: '🇸🇲' },
  { iso2: 'va', name: 'Vatican', dialCode: '+379', flagEmoji: '🇻🇦' },
  { iso2: 'gl', name: 'Greenland', dialCode: '+299', flagEmoji: '🇬🇱' },
  { iso2: 'gi', name: 'Gibraltar', dialCode: '+350', flagEmoji: '🇬🇮' },
  { iso2: 'jm', name: 'Jamaica', dialCode: '+1876', flagEmoji: '🇯🇲' },
  { iso2: 'pr', name: 'Puerto Rico', dialCode: '+1787', flagEmoji: '🇵🇷' },
  { iso2: 'ag', name: 'Antigua-Barbuda', dialCode: '+1268', flagEmoji: '🇦🇬' },
  { iso2: 'ai', name: 'Anguilla', dialCode: '+1264', flagEmoji: '🇦🇮' },
  { iso2: 'bb', name: 'Barbados', dialCode: '+1246', flagEmoji: '🇧🇧' },
  { iso2: 'bs', name: 'Bahamas', dialCode: '+1242', flagEmoji: '🇧🇸' },
  { iso2: 'bm', name: 'Bermuda', dialCode: '+1441', flagEmoji: '🇧🇲' },
  { iso2: 'vg', name: 'British Virgin Islands', dialCode: '+1284', flagEmoji: '🇻🇬' },
  { iso2: 'ca', name: 'Canada', dialCode: '+1', flagEmoji: '🇨🇦' },
  { iso2: 'ky', name: 'Cayman Islands', dialCode: '+1345', flagEmoji: '🇰🇾' },
  { iso2: 'dm', name: 'Dominica', dialCode: '+1767', flagEmoji: '🇩🇲' },
  { iso2: 'do', name: 'Dominican Republic', dialCode: '+1809', flagEmoji: '🇩🇴' },
  { iso2: 'gd', name: 'Grenada', dialCode: '+1473', flagEmoji: '🇬🇩' },
  { iso2: 'gu', name: 'Guam', dialCode: '+1671', flagEmoji: '🇬🇺' },
  { iso2: 'ms', name: 'Montserrat', dialCode: '+1664', flagEmoji: '🇲🇸' },
  { iso2: 'mp', name: 'Northern Mariana Islands', dialCode: '+1670', flagEmoji: '🇲🇵' },
  { iso2: 'kn', name: 'Saint Kitts-Nevis', dialCode: '+1869', flagEmoji: '🇰🇳' },
  { iso2: 'lc', name: 'Saint Lucia', dialCode: '+1758', flagEmoji: '🇱🇨' },
  { iso2: 'vc', name: 'Saint Vincent-Grenadines', dialCode: '+1784', flagEmoji: '🇻🇨' },
  { iso2: 'tt', name: 'Trinidad-Tobago', dialCode: '+1868', flagEmoji: '🇹🇹' },
  { iso2: 'tc', name: 'Turks-Caicos', dialCode: '+1649', flagEmoji: '🇹🇨' },
  { iso2: 'vi', name: 'U.S. Virgin Islands', dialCode: '+1340', flagEmoji: '🇻🇮' },
  { iso2: 'je', name: 'Jersey', dialCode: '+441534', flagEmoji: '🇯🇪' },
  { iso2: 'fk', name: 'Falkland Islands', dialCode: '+500', flagEmoji: '🇫🇰' },
  { iso2: 'bz', name: 'Belize', dialCode: '+501', flagEmoji: '🇧🇿' },
  { iso2: 'gt', name: 'Guatemala', dialCode: '+502', flagEmoji: '🇬🇹' },
  { iso2: 'sv', name: 'El Salvador', dialCode: '+503', flagEmoji: '🇸🇻' },
  { iso2: 'hn', name: 'Honduras', dialCode: '+504', flagEmoji: '🇭🇳' },
  { iso2: 'ni', name: 'Nicaragua', dialCode: '+505', flagEmoji: '🇳🇮' },
  { iso2: 'cr', name: 'Costa Rica', dialCode: '+506', flagEmoji: '🇨🇷' },
  { iso2: 'pa', name: 'Panama', dialCode: '+507', flagEmoji: '🇵🇦' },
  { iso2: 'pm', name: 'Saint Pierre and Miquelon', dialCode: '+508', flagEmoji: '🇵🇲' },
  { iso2: 'ht', name: 'Haiti', dialCode: '+509', flagEmoji: '🇭🇹' },
  { iso2: 'gp', name: 'Guadeloupe', dialCode: '+590', flagEmoji: '🇬🇵' },
  { iso2: 'bo', name: 'Bolivia', dialCode: '+591', flagEmoji: '🇧🇴' },
  { iso2: 'gy', name: 'Guyana', dialCode: '+592', flagEmoji: '🇬🇾' },
  { iso2: 'ec', name: 'Ecuador', dialCode: '+593', flagEmoji: '🇪🇨' },
  { iso2: 'gf', name: 'French Guiana', dialCode: '+594', flagEmoji: '🇬🇫' },
  { iso2: 'py', name: 'Paraguay', dialCode: '+595', flagEmoji: '🇵🇾' },
  { iso2: 'mq', name: 'Martinique', dialCode: '+596', flagEmoji: '🇲🇶' },
  { iso2: 'sr', name: 'Suriname', dialCode: '+597', flagEmoji: '🇸🇷' },
  { iso2: 'uy', name: 'Uruguay', dialCode: '+598', flagEmoji: '🇺🇾' },
  { iso2: 'an', name: 'Netherlands Antilles', dialCode: '+599', flagEmoji: '🇦🇳' },
  { iso2: 'tl', name: 'East Timor', dialCode: '+670', flagEmoji: '🇹🇱' },
  { iso2: 'nf', name: 'Norfolk Island', dialCode: '+672', flagEmoji: '🇳🇫' },
  { iso2: 'sb', name: 'Solomon Islands', dialCode: '+677', flagEmoji: '🇸🇧' },
  { iso2: 'vu', name: 'Vanuatu', dialCode: '+678', flagEmoji: '🇻🇺' },
  { iso2: 'fj', name: 'Fiji', dialCode: '+679', flagEmoji: '🇫🇯' },
  { iso2: 'au', name: 'Australia', dialCode: '+61', flagEmoji: '🇦🇺' },
  { iso2: 'pg', name: 'Papua New Guinea', dialCode: '+675', flagEmoji: '🇵🇬' },
  { iso2: 'ws', name: 'Samoa', dialCode: '+685', flagEmoji: '🇼🇸' },
  { iso2: 'fm', name: 'Micronesia', dialCode: '+691', flagEmoji: '🇫🇲' },
  { iso2: 'mh', name: 'Marshall Islands', dialCode: '+692', flagEmoji: '🇲🇭' },
  { iso2: 'ru', name: 'Russia', dialCode: '+7', flagEmoji: '🇷🇺' },
  { iso2: 'kz', name: 'Kazakhstan', dialCode: '+7', flagEmoji: '🇰🇿' },
  { iso2: 'uz', name: 'Uzbekistan', dialCode: '+998', flagEmoji: '🇺🇿' },
  { iso2: 'tj', name: 'Tajikistan', dialCode: '+992', flagEmoji: '🇹🇯' },
  { iso2: 'tm', name: 'Turkmenistan', dialCode: '+993', flagEmoji: '🇹🇲' },
  { iso2: 'kg', name: 'Kyrgyzstan', dialCode: '+996', flagEmoji: '🇰🇬' },
  { iso2: 'az', name: 'Azerbaijan', dialCode: '+994', flagEmoji: '🇦🇿' },
  { iso2: 'ge', name: 'Georgia', dialCode: '+995', flagEmoji: '🇬🇪' },
  { iso2: 'eh', name: 'Western Sahara', dialCode: '+212', flagEmoji: '🇪🇭' },
  { iso2: 'dz', name: 'Algeria', dialCode: '+213', flagEmoji: '🇩🇿' },
  { iso2: 'tn', name: 'Tunisia', dialCode: '+216', flagEmoji: '🇹🇳' },
  { iso2: 'ly', name: 'Libya', dialCode: '+218', flagEmoji: '🇱🇾' },
  { iso2: 'gm', name: 'Gambia', dialCode: '+220', flagEmoji: '🇬🇲' },
  { iso2: 'sn', name: 'Senegal', dialCode: '+221', flagEmoji: '🇸🇳' },
  { iso2: 'mr', name: 'Mauritania', dialCode: '+222', flagEmoji: '🇲🇷' },
  { iso2: 'ml', name: 'Mali', dialCode: '+223', flagEmoji: '🇲🇱' },
  { iso2: 'gn', name: 'Guinea', dialCode: '+224', flagEmoji: '🇬🇳' },
  { iso2: 'ci', name: 'Ivory Coast', dialCode: '+225', flagEmoji: '🇨🇮' },
  { iso2: 'bf', name: 'Burkina Faso', dialCode: '+226', flagEmoji: '🇧🇫' },
  { iso2: 'ne', name: 'Niger', dialCode: '+227', flagEmoji: '🇳🇪' },
  { iso2: 'tg', name: 'Togo', dialCode: '+228', flagEmoji: '🇹🇬' },
  { iso2: 'bj', name: 'Benin', dialCode: '+229', flagEmoji: '🇧🇯' },
  { iso2: 'mu', name: 'Mauritius', dialCode: '+230', flagEmoji: '🇲🇺' },
  { iso2: 'lr', name: 'Liberia', dialCode: '+231', flagEmoji: '🇱🇷' },
  { iso2: 'sl', name: 'Sierra Leone', dialCode: '+232', flagEmoji: '🇸🇱' },
  { iso2: 'gh', name: 'Ghana', dialCode: '+233', flagEmoji: '🇬🇭' },
  { iso2: 'ng', name: 'Nigeria', dialCode: '+234', flagEmoji: '🇳🇬' },
  { iso2: 'td', name: 'Chad', dialCode: '+235', flagEmoji: '🇹🇩' },
  { iso2: 'cf', name: 'Central African Republic', dialCode: '+236', flagEmoji: '🇨🇫' },
  { iso2: 'cm', name: 'Cameroon', dialCode: '+237', flagEmoji: '🇨🇲' },
  { iso2: 'cv', name: 'Cape Verde', dialCode: '+238', flagEmoji: '🇨🇻' },
  { iso2: 'st', name: 'Sao Tome and Principe', dialCode: '+239', flagEmoji: '🇸🇹' },
  { iso2: 'ga', name: 'Gabon', dialCode: '+241', flagEmoji: '🇬🇦' },
  { iso2: 'cg', name: 'Congo', dialCode: '+242', flagEmoji: '🇨🇬' },
  { iso2: 'cd', name: 'Dem. Rep. of Congo', dialCode: '+243', flagEmoji: '🇨🇩' },
  { iso2: 'ao', name: 'Angola', dialCode: '+244', flagEmoji: '🇦🇴' },
  { iso2: 'gw', name: 'Guinea-Bissau', dialCode: '+245', flagEmoji: '🇬🇼' },
  { iso2: 'io', name: 'British Indian Ocean Territory', dialCode: '+246', flagEmoji: '🇮🇴' },
  { iso2: 'sc', name: 'Seychelles', dialCode: '+248', flagEmoji: '🇸🇨' },
  { iso2: 'sd', name: 'Sudan', dialCode: '+249', flagEmoji: '🇸🇩' },
  { iso2: 'rw', name: 'Rwanda', dialCode: '+250', flagEmoji: '🇷🇼' },
  { iso2: 'et', name: 'Ethiopia', dialCode: '+251', flagEmoji: '🇪🇹' },
  { iso2: 'so', name: 'Somalia', dialCode: '+252', flagEmoji: '🇸🇴' },
  { iso2: 'dj', name: 'Djibouti', dialCode: '+253', flagEmoji: '🇩🇯' },
  { iso2: 'ke', name: 'Kenya', dialCode: '+254', flagEmoji: '🇰🇪' },
  { iso2: 'tz', name: 'Tanzania', dialCode: '+255', flagEmoji: '🇹🇿' },
  { iso2: 'ug', name: 'Uganda', dialCode: '+256', flagEmoji: '🇺🇬' },
  { iso2: 'bi', name: 'Burundi', dialCode: '+257', flagEmoji: '🇧🇮' },
  { iso2: 'mz', name: 'Mozambique', dialCode: '+258', flagEmoji: '🇲🇿' },
  { iso2: 'zm', name: 'Zambia', dialCode: '+260', flagEmoji: '🇿🇲' },
  { iso2: 'mg', name: 'Madagascar', dialCode: '+261', flagEmoji: '🇲🇬' },
  { iso2: 're', name: 'Reunion', dialCode: '+262', flagEmoji: '🇷🇪' },
  { iso2: 'zw', name: 'Zimbabwe', dialCode: '+263', flagEmoji: '🇿🇼' },
  { iso2: 'na', name: 'Namibia', dialCode: '+264', flagEmoji: '🇳🇦' },
  { iso2: 'mw', name: 'Malawi', dialCode: '+265', flagEmoji: '🇲🇼' },
  { iso2: 'ls', name: 'Lesotho', dialCode: '+266', flagEmoji: '🇱🇸' },
  { iso2: 'bw', name: 'Botswana', dialCode: '+267', flagEmoji: '🇧🇼' },
  { iso2: 'sz', name: 'Swaziland', dialCode: '+268', flagEmoji: '🇸🇿' },
  { iso2: 'km', name: 'Comoros', dialCode: '+269', flagEmoji: '🇰🇲' },
  { iso2: 'er', name: 'Eritrea', dialCode: '+291', flagEmoji: '🇪🇷' },
  { iso2: 'aw', name: 'Aruba', dialCode: '+297', flagEmoji: '🇦🇼' },
  { iso2: 'fo', name: 'Faroe Islands', dialCode: '+298', flagEmoji: '🇫🇴' },
  { iso2: 'gr', name: 'Greece', dialCode: '+30', flagEmoji: '🇬🇷' },
  { iso2: 'au', name: 'Australia', dialCode: '+61', flagEmoji: '🇦🇺' },
  { iso2: 'id', name: 'Indonesia', dialCode: '+62', flagEmoji: '🇮🇩' },
  { iso2: 'nz', name: 'New Zealand', dialCode: '+64', flagEmoji: '🇳🇿' },
  { iso2: 'gu', name: 'Guam', dialCode: '+1671', flagEmoji: '🇬🇺' },
  { iso2: 'cn', name: 'China', dialCode: '+86', flagEmoji: '🇨🇳' },
  { iso2: 'jp', name: 'Japan', dialCode: '+81', flagEmoji: '🇯🇵' },
  { iso2: 'vn', name: 'Vietnam', dialCode: '+84', flagEmoji: '🇻🇳' },
  { iso2: 'hk', name: 'Hong Kong', dialCode: '+852', flagEmoji: '🇭🇰' },
  { iso2: 'bd', name: 'Bangladesh', dialCode: '+880', flagEmoji: '🇧🇩' },
  { iso2: 'in', name: 'India', dialCode: '+91', flagEmoji: '🇮🇳' },
  { iso2: 'ir', name: 'Iran', dialCode: '+98', flagEmoji: '🇮🇷' },
  { iso2: 'tr', name: 'Turkey', dialCode: '+90', flagEmoji: '🇹🇷' },
  { iso2: 'us', name: 'United States', dialCode: '+1', flagEmoji: '🇺🇸' },
  { iso2: 'ca', name: 'Canada', dialCode: '+1', flagEmoji: '🇨🇦' },
  { iso2: 'pr', name: 'Puerto Rico', dialCode: '+1787', flagEmoji: '🇵🇷' },
  { iso2: 'ru', name: 'Russia', dialCode: '+7', flagEmoji: '🇷🇺' },
  { iso2: 'kz', name: 'Kazakhstan', dialCode: '+7', flagEmoji: '🇰🇿' },
  { iso2: 'eg', name: 'Egypt', dialCode: '+20', flagEmoji: '🇪🇬' },
  { iso2: 'za', name: 'South Africa', dialCode: '+27', flagEmoji: '🇿🇦' },
  { iso2: 'nl', name: 'Netherlands', dialCode: '+31', flagEmoji: '🇳🇱' },
  { iso2: 'be', name: 'Belgium', dialCode: '+32', flagEmoji: '🇧🇪' },
  { iso2: 'fr', name: 'France', dialCode: '+33', flagEmoji: '🇫🇷' },
  { iso2: 'es', name: 'Spain', dialCode: '+34', flagEmoji: '🇪🇸' },
  { iso2: 'it', name: 'Italy', dialCode: '+39', flagEmoji: '🇮🇹' },
  { iso2: 'gb', name: 'United Kingdom', dialCode: '+44', flagEmoji: '🇬🇧' },
  { iso2: 'de', name: 'Germany', dialCode: '+49', flagEmoji: '🇩🇪' },
  { iso2: 'my', name: 'Malaysia', dialCode: '+60', flagEmoji: '🇲🇾' },
  { iso2: 'sg', name: 'Singapore', dialCode: '+65', flagEmoji: '🇸🇬' },
  { iso2: 'th', name: 'Thailand', dialCode: '+66', flagEmoji: '🇹🇭' },
  { iso2: 'ph', name: 'Philippines', dialCode: '+63', flagEmoji: '🇵🇭' },
  { iso2: 'br', name: 'Brazil', dialCode: '+55', flagEmoji: '🇧🇷' },
  { iso2: 'ar', name: 'Argentina', dialCode: '+54', flagEmoji: '🇦🇷' },
  { iso2: 'mx', name: 'Mexico', dialCode: '+52', flagEmoji: '🇲🇽' },
  { iso2: 'cl', name: 'Chile', dialCode: '+56', flagEmoji: '🇨🇱' },
  { iso2: 'co', name: 'Colombia', dialCode: '+57', flagEmoji: '🇨🇴' },
  { iso2: 'sa', name: 'Saudi Arabia', dialCode: '+966', flagEmoji: '🇸🇦' },
  { iso2: 'ae', name: 'United Arab Emirates', dialCode: '+971', flagEmoji: '🇦🇪' },
  { iso2: 'qa', name: 'Qatar', dialCode: '+974', flagEmoji: '🇶🇦' },
  { iso2: 'il', name: 'Israel', dialCode: '+972', flagEmoji: '🇮🇱' },
  { iso2: 'pk', name: 'Pakistan', dialCode: '+92', flagEmoji: '🇵🇰' },
  { iso2: 'ke', name: 'Kenya', dialCode: '+254', flagEmoji: '🇰🇪' },
  { iso2: 'ng', name: 'Nigeria', dialCode: '+234', flagEmoji: '🇳🇬' },
  { iso2: 'gh', name: 'Ghana', dialCode: '+233', flagEmoji: '🇬🇭' },
  { iso2: 'tz', name: 'Tanzania', dialCode: '+255', flagEmoji: '🇹🇿' },
  { iso2: 'ug', name: 'Uganda', dialCode: '+256', flagEmoji: '🇺🇬' },
  { iso2: 'se', name: 'Sweden', dialCode: '+46', flagEmoji: '🇸🇪' },
  { iso2: 'no', name: 'Norway', dialCode: '+47', flagEmoji: '🇳🇴' },
  { iso2: 'fi', name: 'Finland', dialCode: '+358', flagEmoji: '🇫🇮' },
  { iso2: 'dk', name: 'Denmark', dialCode: '+45', flagEmoji: '🇩🇰' },
  { iso2: 'ie', name: 'Ireland', dialCode: '+353', flagEmoji: '🇮🇪' },
  { iso2: 'pt', name: 'Portugal', dialCode: '+351', flagEmoji: '🇵🇹' },
  { iso2: 'ad', name: 'Andorra', dialCode: '+376', flagEmoji: '🇦🇩' },
  { iso2: 'mc', name: 'Monaco', dialCode: '+377', flagEmoji: '🇲🇨' },
  { iso2: 'sm', name: 'San Marino', dialCode: '+378', flagEmoji: '🇸🇲' },
  { iso2: 'va', name: 'Vatican', dialCode: '+379', flagEmoji: '🇻🇦' },
  { iso2: 'al', name: 'Albania', dialCode: '+355', flagEmoji: '🇦🇱' },
  { iso2: 'mt', name: 'Malta', dialCode: '+356', flagEmoji: '🇲🇹' },
  { iso2: 'is', name: 'Iceland', dialCode: '+354', flagEmoji: '🇮🇸' },
  { iso2: 'lt', name: 'Lithuania', dialCode: '+370', flagEmoji: '🇱🇹' },
  { iso2: 'lv', name: 'Latvia', dialCode: '+371', flagEmoji: '🇱🇻' },
  { iso2: 'ee', name: 'Estonia', dialCode: '+372', flagEmoji: '🇪🇪' },
  { iso2: 'md', name: 'Moldova', dialCode: '+373', flagEmoji: '🇲🇩' },
  { iso2: 'am', name: 'Armenia', dialCode: '+374', flagEmoji: '🇦🇲' },
  { iso2: 'by', name: 'Belarus', dialCode: '+375', flagEmoji: '🇧🇾' },
  { iso2: 'az', name: 'Azerbaijan', dialCode: '+994', flagEmoji: '🇦🇿' },
  { iso2: 'ge', name: 'Georgia', dialCode: '+995', flagEmoji: '🇬🇪' },
  { iso2: 'ua', name: 'Ukraine', dialCode: '+380', flagEmoji: '🇺🇦' },
  { iso2: 'rs', name: 'Serbia', dialCode: '+381', flagEmoji: '🇷🇸' },
  { iso2: 'me', name: 'Montenegro', dialCode: '+382', flagEmoji: '🇲🇪' },
  { iso2: 'hr', name: 'Croatia', dialCode: '+385', flagEmoji: '🇭🇷' },
  { iso2: 'si', name: 'Slovenia', dialCode: '+386', flagEmoji: '🇸🇮' },
  { iso2: 'ba', name: 'Bosnia-Herzegovina', dialCode: '+387', flagEmoji: '🇧🇦' },
  { iso2: 'mk', name: 'Macedonia', dialCode: '+389', flagEmoji: '🇲🇰' },
  { iso2: 'gl', name: 'Greenland', dialCode: '+299', flagEmoji: '🇬🇱' },
  { iso2: 'gi', name: 'Gibraltar', dialCode: '+350', flagEmoji: '🇬🇮' },
  { iso2: 'jm', name: 'Jamaica', dialCode: '+1876', flagEmoji: '🇯🇲' },
  { iso2: 'ag', name: 'Antigua-Barbuda', dialCode: '+1268', flagEmoji: '🇦🇬' },
  { iso2: 'ai', name: 'Anguilla', dialCode: '+1264', flagEmoji: '🇦🇮' },
  { iso2: 'bb', name: 'Barbados', dialCode: '+1246', flagEmoji: '🇧🇧' },
  { iso2: 'bs', name: 'Bahamas', dialCode: '+1242', flagEmoji: '🇧🇸' },
  { iso2: 'bm', name: 'Bermuda', dialCode: '+1441', flagEmoji: '🇧🇲' },
  { iso2: 'vg', name: 'British Virgin Islands', dialCode: '+1284', flagEmoji: '🇻🇬' },
  { iso2: 'ky', name: 'Cayman Islands', dialCode: '+1345', flagEmoji: '🇰🇾' },
  { iso2: 'dm', name: 'Dominica', dialCode: '+1767', flagEmoji: '🇩🇲' },
  { iso2: 'do', name: 'Dominican Republic', dialCode: '+1809', flagEmoji: '🇩🇴' },
  { iso2: 'gd', name: 'Grenada', dialCode: '+1473', flagEmoji: '🇬🇩' },
  { iso2: 'ms', name: 'Montserrat', dialCode: '+1664', flagEmoji: '🇲🇸' },
  { iso2: 'mp', name: 'Northern Mariana Islands', dialCode: '+1670', flagEmoji: '🇲🇵' },
  { iso2: 'kn', name: 'Saint Kitts-Nevis', dialCode: '+1869', flagEmoji: '🇰🇳' },
  { iso2: 'lc', name: 'Saint Lucia', dialCode: '+1758', flagEmoji: '🇱🇨' },
  { iso2: 'vc', name: 'Saint Vincent-Grenadines', dialCode: '+1784', flagEmoji: '🇻🇨' },
  { iso2: 'tt', name: 'Trinidad-Tobago', dialCode: '+1868', flagEmoji: '🇹🇹' },
  { iso2: 'tc', name: 'Turks-Caicos', dialCode: '+1649', flagEmoji: '🇹🇨' },
  { iso2: 'vi', name: 'U.S. Virgin Islands', dialCode: '+1340', flagEmoji: '🇻🇮' },
  { iso2: 'je', name: 'Jersey', dialCode: '+441534', flagEmoji: '🇯🇪' },
  { iso2: 'fk', name: 'Falkland Islands', dialCode: '+500', flagEmoji: '🇫🇰' },
  { iso2: 'bz', name: 'Belize', dialCode: '+501', flagEmoji: '🇧🇿' },
  { iso2: 'gt', name: 'Guatemala', dialCode: '+502', flagEmoji: '🇬🇹' },
  { iso2: 'sv', name: 'El Salvador', dialCode: '+503', flagEmoji: '🇸🇻' },
  { iso2: 'hn', name: 'Honduras', dialCode: '+504', flagEmoji: '🇭🇳' },
  { iso2: 'ni', name: 'Nicaragua', dialCode: '+505', flagEmoji: '🇳🇮' },
  { iso2: 'cr', name: 'Costa Rica', dialCode: '+506', flagEmoji: '🇨🇷' },
  { iso2: 'pa', name: 'Panama', dialCode: '+507', flagEmoji: '🇵🇦' },
  { iso2: 'pm', name: 'Saint Pierre and Miquelon', dialCode: '+508', flagEmoji: '🇵🇲' },
  { iso2: 'ht', name: 'Haiti', dialCode: '+509', flagEmoji: '🇭🇹' },
  { iso2: 'gp', name: 'Guadeloupe', dialCode: '+590', flagEmoji: '🇬🇵' },
  { iso2: 'bo', name: 'Bolivia', dialCode: '+591', flagEmoji: '🇧🇴' },
  { iso2: 'gy', name: 'Guyana', dialCode: '+592', flagEmoji: '🇬🇾' },
  { iso2: 'ec', name: 'Ecuador', dialCode: '+593', flagEmoji: '🇪🇨' },
  { iso2: 'gf', name: 'French Guiana', dialCode: '+594', flagEmoji: '🇬🇫' },
  { iso2: 'py', name: 'Paraguay', dialCode: '+595', flagEmoji: '🇵🇾' },
  { iso2: 'mq', name: 'Martinique', dialCode: '+596', flagEmoji: '🇲🇶' },
  { iso2: 'sr', name: 'Suriname', dialCode: '+597', flagEmoji: '🇸🇷' },
  { iso2: 'uy', name: 'Uruguay', dialCode: '+598', flagEmoji: '🇺🇾' },
  { iso2: 'an', name: 'Netherlands Antilles', dialCode: '+599', flagEmoji: '🇦🇳' },
  { iso2: 'tl', name: 'East Timor', dialCode: '+670', flagEmoji: '🇹🇱' },
  { iso2: 'nf', name: 'Norfolk Island', dialCode: '+672', flagEmoji: '🇳🇫' },
  { iso2: 'sb', name: 'Solomon Islands', dialCode: '+677', flagEmoji: '🇸🇧' },
  { iso2: 'vu', name: 'Vanuatu', dialCode: '+678', flagEmoji: '🇻🇺' },
  { iso2: 'fj', name: 'Fiji', dialCode: '+679', flagEmoji: '🇫🇯' },
  { iso2: 'pg', name: 'Papua New Guinea', dialCode: '+675', flagEmoji: '🇵🇬' },
  { iso2: 'ws', name: 'Samoa', dialCode: '+685', flagEmoji: '🇼🇸' },
  { iso2: 'fm', name: 'Micronesia', dialCode: '+691', flagEmoji: '🇫🇲' },
  { iso2: 'mh', name: 'Marshall Islands', dialCode: '+692', flagEmoji: '🇲🇭' },
  { iso2: 'uz', name: 'Uzbekistan', dialCode: '+998', flagEmoji: '🇺🇿' },
  { iso2: 'tj', name: 'Tajikistan', dialCode: '+992', flagEmoji: '🇹🇯' },
  { iso2: 'tm', name: 'Turkmenistan', dialCode: '+993', flagEmoji: '🇹🇲' },
  { iso2: 'kg', name: 'Kyrgyzstan', dialCode: '+996', flagEmoji: '🇰🇬' },
  { iso2: 'eh', name: 'Western Sahara', dialCode: '+212', flagEmoji: '🇪🇭' },
  { iso2: 'dz', name: 'Algeria', dialCode: '+213', flagEmoji: '🇩🇿' },
  { iso2: 'tn', name: 'Tunisia', dialCode: '+216', flagEmoji: '🇹🇳' },
  { iso2: 'ly', name: 'Libya', dialCode: '+218', flagEmoji: '🇱🇾' },
  { iso2: 'gm', name: 'Gambia', dialCode: '+220', flagEmoji: '🇬🇲' },
  { iso2: 'sn', name: 'Senegal', dialCode: '+221', flagEmoji: '🇸🇳' },
  { iso2: 'mr', name: 'Mauritania', dialCode: '+222', flagEmoji: '🇲🇷' },
  { iso2: 'ml', name: 'Mali', dialCode: '+223', flagEmoji: '🇲🇱' },
  { iso2: 'gn', name: 'Guinea', dialCode: '+224', flagEmoji: '🇬🇳' },
  { iso2: 'ci', name: 'Ivory Coast', dialCode: '+225', flagEmoji: '🇨🇮' },
  { iso2: 'bf', name: 'Burkina Faso', dialCode: '+226', flagEmoji: '🇧🇫' },
  { iso2: 'ne', name: 'Niger', dialCode: '+227', flagEmoji: '🇳🇪' },
  { iso2: 'tg', name: 'Togo', dialCode: '+228', flagEmoji: '🇹🇬' },
  { iso2: 'bj', name: 'Benin', dialCode: '+229', flagEmoji: '🇧🇯' },
  { iso2: 'mu', name: 'Mauritius', dialCode: '+230', flagEmoji: '🇲🇺' },
  { iso2: 'lr', name: 'Liberia', dialCode: '+231', flagEmoji: '🇱🇷' },
  { iso2: 'sl', name: 'Sierra Leone', dialCode: '+232', flagEmoji: '🇸🇱' },
  { iso2: 'td', name: 'Chad', dialCode: '+235', flagEmoji: '🇹🇩' },
  { iso2: 'cf', name: 'Central African Republic', dialCode: '+236', flagEmoji: '🇨🇫' },
  { iso2: 'cm', name: 'Cameroon', dialCode: '+237', flagEmoji: '🇨🇲' },
  { iso2: 'cv', name: 'Cape Verde', dialCode: '+238', flagEmoji: '🇨🇻' },
  { iso2: 'st', name: 'Sao Tome and Principe', dialCode: '+239', flagEmoji: '🇸🇹' },
  { iso2: 'ga', name: 'Gabon', dialCode: '+241', flagEmoji: '🇬🇦' },
  { iso2: 'cg', name: 'Congo', dialCode: '+242', flagEmoji: '🇨🇬' },
  { iso2: 'cd', name: 'Dem. Rep. of Congo', dialCode: '+243', flagEmoji: '🇨🇩' },
  { iso2: 'ao', name: 'Angola', dialCode: '+244', flagEmoji: '🇦🇴' },
  { iso2: 'gw', name: 'Guinea-Bissau', dialCode: '+245', flagEmoji: '🇬🇼' },
  { iso2: 'io', name: 'British Indian Ocean Territory', dialCode: '+246', flagEmoji: '🇮🇴' },
  { iso2: 'sc', name: 'Seychelles', dialCode: '+248', flagEmoji: '🇸🇨' },
  { iso2: 'sd', name: 'Sudan', dialCode: '+249', flagEmoji: '🇸🇩' },
  { iso2: 'rw', name: 'Rwanda', dialCode: '+250', flagEmoji: '🇷🇼' },
  { iso2: 'et', name: 'Ethiopia', dialCode: '+251', flagEmoji: '🇪🇹' },
  { iso2: 'so', name: 'Somalia', dialCode: '+252', flagEmoji: '🇸🇴' },
  { iso2: 'dj', name: 'Djibouti', dialCode: '+253', flagEmoji: '🇩🇯' },
  { iso2: 'tz', name: 'Tanzania', dialCode: '+255', flagEmoji: '🇹🇿' },
  { iso2: 'ug', name: 'Uganda', dialCode: '+256', flagEmoji: '🇺🇬' },
  { iso2: 'bi', name: 'Burundi', dialCode: '+257', flagEmoji: '🇧🇮' },
  { iso2: 'mz', name: 'Mozambique', dialCode: '+258', flagEmoji: '🇲🇿' },
  { iso2: 'zm', name: 'Zambia', dialCode: '+260', flagEmoji: '🇿🇲' },
  { iso2: 'mg', name: 'Madagascar', dialCode: '+261', flagEmoji: '🇲🇬' },
  { iso2: 're', name: 'Reunion', dialCode: '+262', flagEmoji: '🇷🇪' },
  { iso2: 'zw', name: 'Zimbabwe', dialCode: '+263', flagEmoji: '🇿🇼' },
  { iso2: 'na', name: 'Namibia', dialCode: '+264', flagEmoji: '🇳🇦' },
  { iso2: 'mw', name: 'Malawi', dialCode: '+265', flagEmoji: '🇲🇼' },
  { iso2: 'ls', name: 'Lesotho', dialCode: '+266', flagEmoji: '🇱🇸' },
  { iso2: 'bw', name: 'Botswana', dialCode: '+267', flagEmoji: '🇧🇼' },
  { iso2: 'sz', name: 'Swaziland', dialCode: '+268', flagEmoji: '🇸🇿' },
  { iso2: 'km', name: 'Comoros', dialCode: '+269', flagEmoji: '🇰🇲' },
  { iso2: 'er', name: 'Eritrea', dialCode: '+291', flagEmoji: '🇪🇷' },
  { iso2: 'aw', name: 'Aruba', dialCode: '+297', flagEmoji: '🇦🇼' },
  { iso2: 'fo', name: 'Faroe Islands', dialCode: '+298', flagEmoji: '🇫🇴' },
  { iso2: 'gs', name: 'South Georgia and South Sandwich Islands', dialCode: '+500', flagEmoji: '🇬🇸' },
  { iso2: 'cc', name: 'Cocos (Keeling) Islands', dialCode: '+61', flagEmoji: '🇨🇨' },
  { iso2: 'cx', name: 'Christmas Island', dialCode: '+61', flagEmoji: '🇨🇽' },
  { iso2: 'tf', name: 'French Southern Territories', dialCode: '+262', flagEmoji: '🇹🇫' },
  { iso2: 'pf', name: 'French Polynesia', dialCode: '+689', flagEmoji: '🇵🇫' },
  { iso2: 'nr', name: 'Nauru', dialCode: '+674', flagEmoji: '🇳🇷' },
  { iso2: 'tv', name: 'Tuvalu', dialCode: '+688', flagEmoji: '🇹🇻' },
  { iso2: 'ki', name: 'Kiribati', dialCode: '+686', flagEmoji: '🇰🇮' },
  { iso2: 'nu', name: 'Niue', dialCode: '+683', flagEmoji: '🇳🇺' },
  { iso2: 'tk', name: 'Tokelau', dialCode: '+690', flagEmoji: '🇹🇰' },
  { iso2: 'wf', name: 'Wallis and Futuna', dialCode: '+681', flagEmoji: '🇼🇫' },
  { iso2: 'nc', name: 'New Caledonia', dialCode: '+687', flagEmoji: '🇳🇨' },
  { iso2: 'ck', name: 'Cook Islands', dialCode: '+682', flagEmoji: '🇨🇰' },
  { iso2: 'pn', name: 'Pitcairn', dialCode: '+64', flagEmoji: '🇵🇳' },
  { iso2: 'cc', name: 'Cocos Islands', dialCode: '+61', flagEmoji: '🇨🇨' },
  { iso2: 'cx', name: 'Christmas Islands', dialCode: '+61', flagEmoji: '🇨🇽' },
  { iso2: 'tf', name: 'French Southern and Antarctic Lands', dialCode: '+262', flagEmoji: '🇹🇫' },
  { iso2: 'pf', name: 'French Polynesia', dialCode: '+689', flagEmoji: '🇵🇫' },
  { iso2: 'nr', name: 'Nauru', dialCode: '+674', flagEmoji: '🇳🇷' },
  { iso2: 'tv', name: 'Tuvalu', dialCode: '+688', flagEmoji: '🇹🇻' },
  { iso2: 'ki', name: 'Kiribati', dialCode: '+686', flagEmoji: '🇰🇮' },
  { iso2: 'nu', name: 'Niue', dialCode: '+683', flagEmoji: '🇳🇺' },
  { iso2: 'tk', name: 'Tokelau', dialCode: '+690', flagEmoji: '🇹🇰' },
  { iso2: 'wf', name: 'Wallis and Futuna', dialCode: '+681', flagEmoji: '🇼🇫' },
  { iso2: 'nc', name: 'New Caledonia', dialCode: '+687', flagEmoji: '🇳🇨' },
  { iso2: 'ck', name: 'Cook Islands', dialCode: '+682', flagEmoji: '🇨🇰' },
  { iso2: 'pn', name: 'Pitcairn', dialCode: '+64', flagEmoji: '🇵🇳' },
];