import { CountryDialCode } from '../types';

export const COUNTRY_DIAL_CODES: CountryDialCode[] = [
  { iso2: 'kr', name: 'Korea', dialCode: '+82', flagEmoji: '🇰🇷' },
  { iso2: 'us', name: 'United States', dialCode: '+1', flagEmoji: '🇺🇸' },
  { iso2: 'ca', name: 'Canada', dialCode: '+1', flagEmoji: '🇨🇦' },
  { iso2: 'pr', name: 'Puerto Rico', dialCode: '+1', flagEmoji: '🇵🇷' },
  { iso2: 'ru', name: 'Russia', dialCode: '+7', flagEmoji: '🇷🇺' },
  { iso2: 'kz', name: 'Kazakhstan', dialCode: '+7', flagEmoji: '🇰🇿' },
  { iso2: 'eg', name: 'Egypt', dialCode: '+20', flagEmoji: '🇪🇬' },
  { iso2: 'za', name: 'South Africa', dialCode: '+27', flagEmoji: '🇿🇦' },
  { iso2: 'gr', name: 'Greece', dialCode: '+30', flagEmoji: '🇬🇷' },
  { iso2: 'nl', name: 'Netherlands', dialCode: '+31', flagEmoji: '🇳🇱' },
  { iso2: 'be', name: 'Belgium', dialCode: '+32', flagEmoji: '🇧🇪' },
  { iso2: 'fr', name: 'France', dialCode: '+33', flagEmoji: '🇫🇷' },
  { iso2: 'es', name: 'Spain', dialCode: '+34', flagEmoji: '🇪🇸' },
  { iso2: 'it', name: 'Italy', dialCode: '+39', flagEmoji: '🇮🇹' },
  { iso2: 'gb', name: 'United Kingdom', dialCode: '+44', flagEmoji: '🇬🇧' },
  { iso2: 'de', name: 'Germany', dialCode: '+49', flagEmoji: '🇩🇪' },
  { iso2: 'cn', name: 'China', dialCode: '+86', flagEmoji: '🇨🇳' },
  { iso2: 'jp', name: 'Japan', dialCode: '+81', flagEmoji: '🇯🇵' },
  { iso2: 'hk', name: 'Hong Kong', dialCode: '+852', flagEmoji: '🇭🇰' },
  { iso2: 'sg', name: 'Singapore', dialCode: '+65', flagEmoji: '🇸🇬' },
  { iso2: 'au', name: 'Australia', dialCode: '+61', flagEmoji: '🇦🇺' },
  { iso2: 'nz', name: 'New Zealand', dialCode: '+64', flagEmoji: '🇳🇿' },
  { iso2: 'in', name: 'India', dialCode: '+91', flagEmoji: '🇮🇳' },
  { iso2: 'id', name: 'Indonesia', dialCode: '+62', flagEmoji: '🇮🇩' },
  { iso2: 'my', name: 'Malaysia', dialCode: '+60', flagEmoji: '🇲🇾' },
  { iso2: 'th', name: 'Thailand', dialCode: '+66', flagEmoji: '🇹🇭' },
  { iso2: 'vn', name: 'Vietnam', dialCode: '+84', flagEmoji: '🇻🇳' },
  { iso2: 'ph', name: 'Philippines', dialCode: '+63', flagEmoji: '🇵🇭' },
  { iso2: 'br', name: 'Brazil', dialCode: '+55', flagEmoji: '🇧🇷' },
  { iso2: 'ar', name: 'Argentina', dialCode: '+54', flagEmoji: '🇦🇷' },
  { iso2: 'mx', name: 'Mexico', dialCode: '+52', flagEmoji: '🇲🇽' },
  { iso2: 'cl', name: 'Chile', dialCode: '+56', flagEmoji: '🇨🇱' },
  { iso2: 'co', name: 'Colombia', dialCode: '+57', flagEmoji: '🇨🇴' },
  { iso2: 'sa', name: 'Saudi Arabia', dialCode: '+966', flagEmoji: '🇸🇦' },
  { iso2: 'ae', name: 'United Arab Emirates', dialCode: '+971', flagEmoji: '🇦🇪' },
  { iso2: 'qa', name: 'Qatar', dialCode: '+974', flagEmoji: '🇶🇦' },
  { iso2: 'tr', name: 'Turkey', dialCode: '+90', flagEmoji: '🇹🇷' },
  { iso2: 'il', name: 'Israel', dialCode: '+972', flagEmoji: '🇮🇱' },
  { iso2: 'pk', name: 'Pakistan', dialCode: '+92', flagEmoji: '🇵🇰' },
  { iso2: 'bd', name: 'Bangladesh', dialCode: '+880', flagEmoji: '🇧🇩' },
  { iso2: 'ir', name: 'Iran', dialCode: '+98', flagEmoji: '🇮🇷' },
  { iso2: 'ke', name: 'Kenya', dialCode: '+254', flagEmoji: '🇰🇪' },
  { iso2: 'ng', name: 'Nigeria', dialCode: '+234', flagEmoji: '🇳🇬' },
  { iso2: 'gh', name: 'Ghana', dialCode: '+233', flagEmoji: '🇬🇭' },
  { iso2: 'tz', name: 'Tanzania', dialCode: '+255', flagEmoji: '🇹🇿' },
  { iso2: 'ug', name: 'Uganda', dialCode: '+256', flagEmoji: '🇺🇬' },
  { iso2: 'se', name: 'Sweden', dialCode: '+46', flagEmoji: '🇸🇪' },
  { iso2: 'no', name: 'Norway', dialCode: '+47', flagEmoji: '🇳🇴' },
  { iso2: 'fi', name: 'Finland', dialCode: '+358', flagEmoji: '🇫🇮' },
  { iso2: 'dk', name: 'Denmark', dialCode: '+45', flagEmoji: '🇩🇰' },
];

